### ISSUE TITLE
(和前一位相同的数据集问题)CIFAR10DVS和NCAL101运行报错

### ISSUE THREAD

**Issue by li17855320680** [ridgerchu/TCJA#3]
作者你好，我在运行源码时，将三个数据集都下好放到指定位置上，发现只有dvs128可以成功运行，另外两个在数据集开始处理的时候就会报相同的错误，以下是CIFAR10DVS开始时的运行错误，感觉是源码数据抽取时有问题，请作者帮忙看下，并能更新下源码，万分感谢！
![Snipaste_2023-07-19_17-36-18](https://github.com/ridgerchu/TCJA/assets/101408583/90c352e1-bd99-406c-b0a7-6b984374a6bd)
```python
Namespace(T=20, T_max=1024, add_dict=None, amp=False, b=2, channels=128, data_dir='/home/cmr/LHH/TCJA/path/to/CIFAR10DVS', device='cuda:0', dts_cache='./dts_cache', epochs=1024, gamma=0.1, j=20, loss='mse', lr=0.001, lr_scheduler='CosALR', mixup=False, momentum=0.9, opt='Adam', out_dir='runs/cifar10dvs', resume=None, step_size=32)
VGGNet(
  (conv): Sequential(
    (0): SeqToANNContainer(
      (0): AdaptiveAvgPool2d(output_size=48)
    )
    (1): SeqToANNContainer(
      (0): Conv2d(2, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (2): MultiStepLIFNode(
      v_threshold=1.0, v_reset=0.0, v_rest=0.0, detach_reset=True, tau=2.0, backend=torch
      (surrogate_function): PiecewiseQuadratic(alpha=1.0, spiking=True)
    )
    (3): SeqToANNContainer(
      (0): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (4): MultiStepLIFNode(
      v_threshold=1.0, v_reset=0.0, v_rest=0.0, detach_reset=True, tau=2.0, backend=torch
      (surrogate_function): PiecewiseQuadratic(alpha=1.0, spiking=True)
    )
    (5): SeqToANNContainer(
      (0): AvgPool2d(kernel_size=2, stride=2, padding=0)
    )
    (6): SeqToANNContainer(
      (0): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (7): MultiStepLIFNode(
      v_threshold=1.0, v_reset=0.0, v_rest=0.0, detach_reset=True, tau=2.0, backend=torch
      (surrogate_function): PiecewiseQuadratic(alpha=1.0, spiking=True)
    )
    (8): SeqToANNContainer(
      (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (9): MultiStepLIFNode(
      v_threshold=1.0, v_reset=0.0, v_rest=0.0, detach_reset=True, tau=2.0, backend=torch
      (surrogate_function): PiecewiseQuadratic(alpha=1.0, spiking=True)
    )
    (10): SeqToANNContainer(
      (0): AvgPool2d(kernel_size=2, stride=2, padding=0)
    )
    (11): SeqToANNContainer(
      (0): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (12): MultiStepLIFNode(
      v_threshold=1.0, v_reset=0.0, v_rest=0.0, detach_reset=True, tau=2.0, backend=torch
      (surrogate_function): PiecewiseQuadratic(alpha=1.0, spiking=True)
    )
    (13): SeqToANNContainer(
      (0): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (14): MultiStepLIFNode(
      v_threshold=1.0, v_reset=0.0, v_rest=0.0, detach_reset=True, tau=2.0, backend=torch
      (surrogate_function): PiecewiseQuadratic(alpha=1.0, spiking=True)
    )
    (15): TCJA(
      (conv): Conv1d(10, 10, kernel_size=(4,), stride=(1,), padding=same, bias=False)
      (conv_c): Conv1d(512, 512, kernel_size=(4,), stride=(1,), padding=same, bias=False)
      (sigmoid): Sigmoid()
    )
    (16): SeqToANNContainer(
      (0): AvgPool2d(kernel_size=2, stride=2, padding=0)
    )
    (17): SeqToANNContainer(
      (0): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (18): MultiStepLIFNode(
      v_threshold=1.0, v_reset=0.0, v_rest=0.0, detach_reset=True, tau=2.0, backend=torch
      (surrogate_function): PiecewiseQuadratic(alpha=1.0, spiking=True)
    )
    (19): SeqToANNContainer(
      (0): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (20): MultiStepLIFNode(
      v_threshold=1.0, v_reset=0.0, v_rest=0.0, detach_reset=True, tau=2.0, backend=torch
      (surrogate_function): PiecewiseQuadratic(alpha=1.0, spiking=True)
    )
    (21): TCJA(
      (conv): Conv1d(10, 10, kernel_size=(4,), stride=(1,), padding=same, bias=False)
      (conv_c): Conv1d(512, 512, kernel_size=(4,), stride=(1,), padding=same, bias=False)
      (sigmoid): Sigmoid()
    )
    (22): SeqToANNContainer(
      (0): AvgPool2d(kernel_size=2, stride=2, padding=0)
    )
  )
  (fc): Sequential(
    (0): Flatten(start_dim=2, end_dim=-1)
    (1): SeqToANNContainer(
      (0): Linear(in_features=4608, out_features=10, bias=True)
    )
  )
)
0
Mkdir [/home/cmr/LHH/TCJA/path/to/CIFAR10DVS/frames_number_20_split_by_number].
Mkdir [/home/cmr/LHH/TCJA/path/to/CIFAR10DVS/frames_number_20_split_by_number/dog].
Mkdir [/home/cmr/LHH/TCJA/path/to/CIFAR10DVS/frames_number_20_split_by_number/bird].
Mkdir [/home/cmr/LHH/TCJA/path/to/CIFAR10DVS/frames_number_20_split_by_number/deer].
Mkdir [/home/cmr/LHH/TCJA/path/to/CIFAR10DVS/frames_number_20_split_by_number/frog].
Mkdir [/home/cmr/LHH/TCJA/path/to/CIFAR10DVS/frames_number_20_split_by_number/ship].
Mkdir [/home/cmr/LHH/TCJA/path/to/CIFAR10DVS/frames_number_20_split_by_number/truck].
Mkdir [/home/cmr/LHH/TCJA/path/to/CIFAR10DVS/frames_number_20_split_by_number/cat].
Mkdir [/home/cmr/LHH/TCJA/path/to/CIFAR10DVS/frames_number_20_split_by_number/horse].
Mkdir [/home/cmr/LHH/TCJA/path/to/CIFAR10DVS/frames_number_20_split_by_number/automobile].
Mkdir [/home/cmr/LHH/TCJA/path/to/CIFAR10DVS/frames_number_20_split_by_number/airplane].
Start ThreadPoolExecutor with max workers = [16].
Used time = [0.0s].
Traceback (most recent call last):
  File "src/cifar10dvs.py", line 355, in <module>
    main()
  File "src/cifar10dvs.py", line 166, in main
    origin_set = CIFAR10DVS(root=args.data_dir, data_type='frame', frames_number=args.T, split_by='number',
  File "/home/cmr/LHH/TCJA/src/spikingjelly/datasets/cifar10_dvs.py", line 128, in __init__
    super().__init__(root, None, data_type, frames_number, split_by, duration, custom_integrate_function, custom_integrated_frames_dir_name, transform,
  File "/home/cmr/LHH/TCJA/src/spikingjelly/datasets/__init__.py", line 874, in __init__
    super().__init__(root=_root, loader=_loader, extensions=('.npz', ), transform=_transform,
  File "/home/fang/anaconda3/envs/sp-torch/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 146, in __init__
    samples = self.make_dataset(self.root, class_to_idx, extensions, is_valid_file)
  File "/home/fang/anaconda3/envs/sp-torch/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 190, in make_dataset
    return make_dataset(directory, class_to_idx, extensions=extensions, is_valid_file=is_valid_file)
  File "/home/fang/anaconda3/envs/sp-torch/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 103, in make_dataset
    raise FileNotFoundError(msg)
FileNotFoundError: Found no valid file for the classes airplane, automobile, bird, cat, deer, dog, frog, horse, ship, truck. Supported extensions are: .npz

**Comment by ridgerchu** [comment]
你好，
这个问题似乎是由于数据集下载出错所导致的。在上一个issue中，我已经把数据集链接放在了回复中，请使用这一链接下载并尝试解压到你所指定的dataset路径中。希望能够帮到你！

**Comment by li17855320680** [comment]
好的，万分感谢，我试一下！
